-- Generic
vim.o.number         = true
vim.o.cursorline     = true
-- vim.o.signcolumn  = "yes"
vim.o.incsearch      = true
vim.o.ignorecase     = true
vim.o.hlsearch       = true
vim.o.scrolloff      = 20
vim.o.showmode       = false
vim.o.splitright     = true
vim.o.termguicolors  = true
vim.o.tabstop        = 4
vim.o.softtabstop    = 4
vim.o.shiftwidth     = 4
vim.o.autoindent     = true
vim.o.smartindent    = true
vim.o.breakindent    = true
vim.o.linebreak      = true
vim.o.wrap           = true
vim.o.showcmd        = true
vim.o.relativenumber = true
vim.noswapfile       = true
